name: cupertino_text_button
description: Buttons that look like cupertino ones.
version: 0.0.1+2
homepage: https://github.com/nivisi/cupertino_text_button
repository: https://github.com/nivisi/cupertino_text_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0